/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include <HShortCut.h>
/* Header for class cn_hisdar_lib_local_Windows */

#ifndef _Included_cn_hisdar_lib_local_Windows
#define _Included_cn_hisdar_lib_local_Windows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hisdar_lib_local_Windows
 * Method:    createShortCut
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_hisdar_lib_local_Windows_createShortCut
	(JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
